In [122]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [123]:
data = pd.read_csv(r"C:\Users\GODFREY\Downloads\energy_data.csv")

In [124]:
data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.60,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.48,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.37,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.25,733.8,92.0,6.000000,51.500000,5.0,45.410390,45.410390
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.13,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [125]:
data.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.412580,755.522602,79.750418,4.039752,38.330834,3.760995,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.318464,7.399441,14.901088,2.451221,11.794719,4.195248,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.670000,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.920000,756.100000,83.666667,3.666667,40.000000,3.430000,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.400000,760.933333,91.666667,5.500000,40.000000,6.570000,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [126]:
data.shape

(19735, 29)

In [127]:
data.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [128]:
data.duplicated().sum()

0

In [129]:
mydata = data.drop(["rv1", "rv2", "date", "lights"], axis = 1)

In [130]:
mydata.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,18.2,48.900000,17.033333,45.53,6.60,733.5,92.0,7.000000,63.000000,5.3
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,18.2,48.863333,17.066667,45.56,6.48,733.6,92.0,6.666667,59.166667,5.2
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,18.2,48.730000,17.000000,45.50,6.37,733.7,92.0,6.333333,55.333333,5.1
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,18.1,48.590000,17.000000,45.40,6.25,733.8,92.0,6.000000,51.500000,5.0
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,18.1,48.590000,17.000000,45.40,6.13,733.9,92.0,5.666667,47.666667,4.9

In [131]:
mydata.corr()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint
Appliances,1.000000,0.055447,0.086031,0.120073,-0.060465,0.085060,0.036292,0.040281,0.016965,0.019760,...,0.039572,-0.094039,0.010010,-0.051462,0.099155,-0.034885,-0.152282,0.087122,0.000230,0.015357
T1,0.055447,1.000000,0.164006,0.836834,-0.002509,0.892402,-0.028550,0.877001,0.097861,0.885247,...,0.825413,-0.006441,0.844777,0.071756,0.682854,-0.150574,-0.345481,-0.087654,-0.076210,0.571333
RH_1,0.086031,0.164006,1.000000,0.269839,0.797535,0.253230,0.844677,0.106180,0.880359,0.205797,...,-0.030053,0.736196,0.115263,0.764001,0.340788,-0.293957,0.274126,0.204932,-0.021057,0.639125
T2,0.120073,0.836834,0.269839,1.000000,-0.165610,0.735245,0.121497,0.762066,0.231563,0.720550,...,0.578191,0.068534,0.675535,0.157346,0.792247,-0.133028,-0.505291,0.052495,-0.069721,0.582632
RH_2,-0.060465,-0.002509,0.797535,-0.165610,1.000000,0.137319,0.678326,-0.047304,0.721435,0.110409,...,-0.041023,0.679777,0.054544,0.676467,0.033703,-0.255646,0.584911,0.069190,-0.005368,0.499154
T3,0.085060,0.892402,0.253230,0.735245,0.137319,1.000000,-0.011234,0.852778,0.122737,0.888169,...,0.795283,0.044427,0.901324,0.134602,0.699420,-0.189974,-0.281718,-0.100776,-0.102310,0.645909
RH_3,0.036292,-0.028550,0.844677,0.121497,0.678326,-0.011234,1.000000,-0.140457,0.898978,-0.050062,...,-0.283228,0.828822,-0.195270,0.833538,0.118237,-0.233274,0.356192,0.263188,0.017041,0.414398
T4,0.040281,0.877001,0.106180,0.762066,-0.047304,0.852778,-0.140457,1.000000,-0.048650,0.871813,...,0.796256,-0.095192,0.889439,-0.025549,0.663479,-0.075292,-0.388602,-0.185747,-0.104768,0.519504
RH_4,0.016965,0.097861,0.880359,0.231563,0.721435,0.122737,0.898978,-0.048650,1.000000,0.091812,...,-0.167066,0.847259,-0.044518,0.856591,0.293307,-0.250748,0.336813,0.300192,0.002636,0.616508
T5,0.019760,0.885247,0.205797,0.720550,0.110409,0.888169,-0.050062,0.871813,0.091812,1.000000,...,0.824981,0.016388,0.911055,0.072308,0.651335,-0.170999,-0.273953,-0.145011,-0.084164,0.588393
RH_5,0.006955,-0.014782,0.303258,0.029595,0.250271,-0.066355,0.375422,-0.076489,0.352591,0.032786,...,-0.086991,0.359840,-0.138509,0.272197,-0.053090,-0.119327,0.185941,0.082044,-0.013133,0.078164
T6,0.117638,0.654769,0.316141,0.801186,-0.009670,0.686882,0.076833,0.652350,0.259047,0.629161,...,0.482836,0.073721,0.667177,0.184424,0.974778,-0.141643,-0.569119,0.169185,-0.081313,0.764242
RH_6,-0.083178,-0.615045,0.245126,-0.580372,0.389933,-0.647672,0.514912,-0.703149,0.392178,-0.632384,...,-0.665869,0.489580,-0.738940,0.391943,-0.641573,-0.065814,0.718587,0.098317,0.108705,-0.260426
T7,0.025801,0.838705,0.021397,0.663660,-0.051422,0.847374,-0.250090,0.877763,-0.131204,0.870624,...,0.882123,-0.209961,0.944776,-0.077690,0.631300,-0.097724,-0.411213,-0.185892,-0.110089,0.466664
RH_7,-0.055642,0.135182,0.801122,0.229212,0.690584,0.172624,0.832685,0.043527,0.894301,0.148905,...,-0.124102,0.883984,0.028055,0.858686,0.294222,-0.265850,0.378519,0.212979,-0.007184,0.641857
T8,0.039572,0.825413,-0.030053,0.578191,-0.041023,0.795283,-0.283228,0.796256,-0.167066,0.824981,...,1.000000,-0.209532,0.869338,-0.156820,0.502850,-0.162855,-0.300438,-0.218876,-0.060098,0.391839
RH_8,-0.094039,-0.006441,0.736196,0.068534,0.679777,0.044427,0.828822,-0.095192,0.847259,0.016388,...,-0.209532,1.000000,-0.113014,0.855812,0.117164,-0.225591,0.487355,0.202380,0.046178,0.501781
T9,0.010010,0.844777,0.115263,0.675535,0.054544,0.901324,-0.195270,0.889439,-0.044518,0.911055,...,0.869338,-0.113014,1.000000,-0.008683,0.668218,-0.156828,-0.318848,-0.177756,-0.103915,0.581517
RH_9,-0.051462,0.071756,0.764001,0.157346,0.676467,0.134602,0.833538,-0.025549,0.856591,0.072308,...,-0.156820,0.855812,-0.008683,1.000000,0.223282,-0.183739,0.359377,0.238655,0.008667,0.540337
T_out,0.099155,0.682854,0.340788,0.792247,0.033703,0.699420,0.118237,0.663479,0.293307,0.651335,...,0.502850,0.117164,0.668218,0.223282,1.000000,-0.143258,-0.574186,0.192940,-0.077367,0.790664
Press_mm_hg,-0.034885,-0.150574,-0.293957,-0.133028,-0.255646,-0.189974,-0.233274,-0.075292,-0.250748,-0.170999,...,-0.162855,-0.225591,-0.156828,-0.183739,-0.143258,1.000000,-0.092017,-0.235032,0.040315,-0.244103
RH_out,-0.152282,-0.345481,0.274126,-0.505291,0.584911,-0.281718,0.356192,-0.388602,0.336813,-0.273953,...,-0.300438,0.487355,-0.318848,0.359377,-0.574186,-0.092017,1.000000,-0.176458,0.083125,0.036509
Windspeed,0.087122,-0.087654,0.204932,0.052495,0.069190,-0.100776,0.263188,-0.185747,0.300192,-0.145011,...,-0.218876,0.202380,-0.177756,0.238655,0.192940,-0.235032,-0.176458,1.000000,-0.007516,0.125926
Visibility,0.000230,-0.076210,-0.021057,-0.069721,-0.005368,-0.102310,0.017041,-0.104768,0.002636,-0.084164,...,-0.060098,0.046178,-0.103915,0.008667,-0.077367,0.040315,0.083125,-0.007516,1.000000,-0.042194
Tdewpoint,0.015357,0.571333,0.639125,0.582632,0.499154,0.645909,0.414398,0.519504,0.616508,0.588393,...,0.391839,0.501781,0.581517,0.540337,0.790664,-0.244103,0.036509,0.125926,-0.042194,1.000000

In [132]:
X = mydata['T2'].values.reshape(-1, 1)
y = mydata['T6'].values

model = LinearRegression()
model.fit(X, y)

r2 = model.score(X, y)

print("R-squared value:", round(r2, 2))

R-squared value: 0.64

In [133]:
scaler = MinMaxScaler()
new_data = pd.DataFrame(scaler.fit_transform(mydata), columns = mydata.columns)
new_data.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.173329,0.661412,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.173329,0.660155,0.226500,0.678532,0.369132,0.100000,0.894737,0.476190,0.894872,0.533937
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.173329,0.655586,0.219563,0.676049,0.365595,0.102326,0.894737,0.452381,0.835897,0.529412
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.164175,0.650788,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.164175,0.650788,0.219563,0.671909,0.357878,0.106977,0.894737,0.404762,0.717949,0.520362

In [134]:
X = new_data.drop("Appliances", axis = 1)
Y = new_data["Appliances"]

In [135]:
print(X.head())
print(Y.head())

        T1      RH_1        T2      RH_2        T3      RH_3        T4  \
0  0.32735  0.566187  0.225345  0.684038  0.215188  0.746066  0.351351
1  0.32735  0.541326  0.225345  0.682140  0.215188  0.748871  0.351351
2  0.32735  0.530502  0.225345  0.679445  0.215188  0.755569  0.344745
3  0.32735  0.524080  0.225345  0.678414  0.215188  0.758685  0.341441
4  0.32735  0.531419  0.225345  0.676727  0.215188  0.758685  0.341441

       RH_4        T5      RH_5  ...        T8      RH_8        T9      RH_9  \
0  0.764262  0.175506  0.381691  ...  0.173329  0.661412  0.223032  0.677290
1  0.782437  0.175506  0.381691  ...  0.173329  0.660155  0.226500  0.678532
2  0.778062  0.175506  0.380037  ...  0.173329  0.655586  0.219563  0.676049
3  0.770949  0.175506  0.380037  ...  0.164175  0.650788  0.219563  0.671909
4  0.762697  0.178691  0.380037  ...  0.164175  0.650788  0.219563  0.671909

      T_out  Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint
0  0.372990     0.097674  0.894737   0.500000    0.953846   0.538462
1  0.369132     0.100000  0.894737   0.476190    0.894872   0.533937
2  0.365595     0.102326  0.894737   0.452381    0.835897   0.529412
3  0.361736     0.104651  0.894737   0.428571    0.776923   0.524887
4  0.357878     0.106977  0.894737   0.404762    0.717949   0.520362

[5 rows x 24 columns]
0    0.046729
1    0.046729
2    0.037383
3    0.037383
4    0.046729
Name: Appliances, dtype: float64

In [136]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [137]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [138]:
predicted_data = model.predict(x_test)
predicted_data

array([0.03318658, 0.24416073, 0.034772  , ..., 0.06799452, 0.0998283 ,
       0.05807734])

In [139]:
# RSS
rss = np.sum(np.square(y_test - predicted_data))
round(rss, 2)

45.33

In [140]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_data)
round(mae, 3)

0.05

In [141]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_data))
round(rmse, 3)

0.087

In [142]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_data)
round(r2_score, 2)

0.15

In [143]:

def get_weights_df(model, feat, col_name):

  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(model, x_train, 'Linear_Model_Weight')
linear_model_weights

       Features  Linear_Model_Weight
0          RH_2            -0.456553
1         T_out            -0.321847
2            T2            -0.236077
3            T9            -0.189903
4          RH_8            -0.157566
5        RH_out            -0.077650
6          RH_7            -0.044571
7          RH_9            -0.039887
8            T5            -0.015712
9            T1            -0.003301
10  Press_mm_hg             0.006845
11           T7             0.010401
12   Visibility             0.012288
13         RH_5             0.015947
14         RH_4             0.026414
15           T4             0.029041
16    Windspeed             0.029187
17         RH_6             0.038067
18         RH_3             0.096035
19           T8             0.101945
20    Tdewpoint             0.117757
21           T6             0.236389
22           T3             0.290531
23         RH_1             0.553471

In [144]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)
predicted_data = ridge_model.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, predicted_data))
rmse

0.08751972889376865

In [145]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)
feature_weights = lasso_model.coef_

non_zero_features = sum(feature_weights != 0)
print("Number of features with non-zero weights:", non_zero_features)

Number of features with non-zero weights: 4

In [146]:
predicted_data = lasso_model.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, predicted_data))
print("RMSE with Lasso regression:", round(rmse, 3))

RMSE with Lasso regression: 0.094